import { PropsWithChildren } from 'react';
import { AdminHeader } from './home/_components/AdminHeader';
import { AdminFooter } from './home/_components/AdminFooter';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};

const Layout = ({ children }: PropsWithChildren) => {
  return (
    <div className="flex min-h-screen w-full flex-col bg-gray-200">
      <AdminHeader />
      <div className="min-h-0 flex-1 overflow-x-auto">{children}</div>
      <AdminFooter />
    </div>
  );
};

export default Layout;
