import { PropsWithChildren } from 'react';

import { Footer } from '@/components/footer/Footer';
import { Header } from '@/app/user/home/_components/header/Header';

export const metadata = {
  title: 'Welcome to example-frontend',
  description: 'Generated by create-nx-workspace',
};
const UserLayout = ({ children }: PropsWithChildren) => {
  return (
    <div className="mx-auto flex min-h-screen w-full max-w-[1334px] flex-col bg-zinc-950">
      <Header />
      <div className="min-h-0 flex-1">{children}</div>
      <Footer />
    </div>
  );
};
export default UserLayout;
